# -*- coding: utf-8 -*-
"""Session 4 _0984

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oRa74YVQYc6oKTsVhSXQWLUEgUVA-zeq
"""

print("Hello World!")

def calculate_factorial():
    try:
        n_str = input("Enter a number: ")
        n = int(n_str)

        if n < 0:
            print("Factorial is not defined for negative numbers.")
        elif n == 0:
            print("Factorial of 0 = 1")
        else:
            factorial_result = 1
            for i in range(1, n + 1):
                factorial_result *= i
            print(f"Factorial of {n} = {factorial_result}")
    except ValueError:
        print("Invalid input. Please enter an integer.")

calculate_factorial()

n_str = input("Enter the number of terms: ")
try:
    n = int(n_str)

    if n <= 0:
        print("Please enter a positive integer.")
    else:
        first = 0
        second = 1

        print("Fibonacci Series:", end=" ")

        for i in range(n):
            print(first, end=" ")
            next_term = first + second
            first = second
            second = next_term
        print()
except ValueError:
    print("Invalid input. Please enter an integer.")

class Student:
    def __init__(self, name, roll_no, marks):
        self.name = name
        self.roll_no = roll_no
        self.marks = marks

s = Student("Rahul", 4, 87.9)

print(f"Name: {s.name}")
print(f"Roll No: {s.roll_no}")
print(f"Marks: {s.marks:.1f}")