# -*- coding: utf-8 -*-
"""Session 4 _0984

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oRa74YVQYc6oKTsVhSXQWLUEgUVA-zeq
"""

print("Hello World!")

def calculate_factorial():
    try:
        n_str = input("Enter a number: ")
        n = int(n_str)

        if n < 0:
            print("Factorial is not defined for negative numbers.")
        elif n == 0:
            print("Factorial of 0 = 1")
        else:
            factorial_result = 1
            for i in range(1, n + 1):
                factorial_result *= i
            print(f"Factorial of {n} = {factorial_result}")
    except ValueError:
        print("Invalid input. Please enter an integer.")

calculate_factorial()

